version: '3'
services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid

#to create an instance of the docker above, use the command:
#docker compose up -d 

#to stop an instance of the docker above, use the command:
#docker compose stop

